/*
* DON'T TOUCH!
* This file is generated by python script AUTOMATICALLY!
*
* Generated base on: ./json_template\tdx_xyzq_history_deal_t.json
* Type name: tdx_xyzq_history_deal_t
* Tester:    int tdx_xyzq_history_deal_t_tester();
*
* Json keep-word: 
    "__default_value_fields__": [], # Take value in .json file as the default value of cpp variable
    "__optional_fields__": [], # Not require to present to .json file, but always in cpp struct
    "__assign_type_fields__": {"field":"cpp-type"}, # Assign specal cpp-type of field, but not infer automatically as default.
    "__assign_enum_fields__": {"field":"enum-type"}, # Assign specal enum-type of field, but not infer automatically as default.
                              enum-type need have implemented <enum-type>_toSting() & <enum-type>_fromString() functions.
    "__assign_set_lists__": [], # Take list in .json file as std::set<>, but not std::vector<> as default
    "__cpp_eq_eclude__":[],     # List of variables not involved in equal compare.
    "__comment__xxx":"", # Add comment line
    "__sqlite_capable__":"", # enable sqlite tableIO autogen
    "__sqlite_primary__":"", # assign the primary key of sqlite, if not assigned, first existing col of [ 'id', 'date', 'mktCode', 'datetime', 'code'] will be assigned automatically.
* Script author: ChinSaiki<chinsaiki@outlook.com>
*/
#pragma once


#include <assert.h>
#include "common/s4json_util.h"
#include "common/s4logger.h"
#include "types/s4type.h"
#include "types/s4convertors.h"

#include <set>
#include <list>
#include <vector>

namespace S4 {

/* type */
struct tdx_xyzq_history_deal_t {
	time_date_t date;	//	20200507
	std::string time_format;	//	19:55:30
	time_utcSec_t time_utcSec;	//	123
	std::string stock_code;	//	002988
	std::string stock_name;	//	豪美新材
	int64_t id;	//	26
	std::string opt_type;	//	买入
	fprice_t deal_price;	//	0.0
	vol_share_t deal_vol;	//	27
	amount_t deal_amount;	//	0.0
	amount_t commission;	//	0.0
	amount_t stamp_duty;	//	0.0
	amount_t transfer_fee;	//	0.0
	amount_t other_fees;	//	0.0
	std::string remarks;	//	起始配号:226168906

	/* from json */
	static bool from_json(const nlohmann::json& json_var, tdx_xyzq_history_deal_t& tdx_xyzq_history_deal_t_var){
		try{
			if(json_var.find("date") != json_var.end()){
				try{
					const auto& json_var_date = json_var.at("date");
					json_var_date.get_to(tdx_xyzq_history_deal_t_var.date);
				}catch(const std::exception& e){
					ERR("Convert \"date\" to \"time_date_t\" fail! e={:}", e.what());
					throw e;
				}
			}else{
				ERR("\"date\" not found in json!");
				return false;
			}
			if(json_var.find("time_format") != json_var.end()){
				try{
					const auto& json_var_time_format = json_var.at("time_format");
					json_var_time_format.get_to(tdx_xyzq_history_deal_t_var.time_format);
				}catch(const std::exception& e){
					ERR("Convert \"time_format\" to \"std::string\" fail! e={:}", e.what());
					throw e;
				}
			}else{
				ERR("\"time_format\" not found in json!");
				return false;
			}
			if(json_var.find("time_utcSec") != json_var.end()){
				try{
					const auto& json_var_time_utcSec = json_var.at("time_utcSec");
					json_var_time_utcSec.get_to(tdx_xyzq_history_deal_t_var.time_utcSec);
				}catch(const std::exception& e){
					ERR("Convert \"time_utcSec\" to \"time_utcSec_t\" fail! e={:}", e.what());
					throw e;
				}
			}else{
				ERR("\"time_utcSec\" not found in json!");
				return false;
			}
			if(json_var.find("stock_code") != json_var.end()){
				try{
					const auto& json_var_stock_code = json_var.at("stock_code");
					json_var_stock_code.get_to(tdx_xyzq_history_deal_t_var.stock_code);
				}catch(const std::exception& e){
					ERR("Convert \"stock_code\" to \"std::string\" fail! e={:}", e.what());
					throw e;
				}
			}else{
				ERR("\"stock_code\" not found in json!");
				return false;
			}
			if(json_var.find("stock_name") != json_var.end()){
				try{
					const auto& json_var_stock_name = json_var.at("stock_name");
					json_var_stock_name.get_to(tdx_xyzq_history_deal_t_var.stock_name);
				}catch(const std::exception& e){
					ERR("Convert \"stock_name\" to \"std::string\" fail! e={:}", e.what());
					throw e;
				}
			}else{
				ERR("\"stock_name\" not found in json!");
				return false;
			}
			if(json_var.find("id") != json_var.end()){
				try{
					const auto& json_var_id = json_var.at("id");
					if (json_var_id.is_string())
					    tdx_xyzq_history_deal_t_var.id = IntConvertor::convert(json_var_id.get<std::string>());
					else
					    json_var_id.get_to(tdx_xyzq_history_deal_t_var.id);
				}catch(const std::exception& e){
					ERR("Convert \"id\" to \"int64_t\" fail! e={:}", e.what());
					throw e;
				}
			}else{
				ERR("\"id\" not found in json!");
				return false;
			}
			if(json_var.find("opt_type") != json_var.end()){
				try{
					const auto& json_var_opt_type = json_var.at("opt_type");
					json_var_opt_type.get_to(tdx_xyzq_history_deal_t_var.opt_type);
				}catch(const std::exception& e){
					ERR("Convert \"opt_type\" to \"std::string\" fail! e={:}", e.what());
					throw e;
				}
			}else{
				ERR("\"opt_type\" not found in json!");
				return false;
			}
			if(json_var.find("deal_price") != json_var.end()){
				try{
					const auto& json_var_deal_price = json_var.at("deal_price");
					json_var_deal_price.get_to(tdx_xyzq_history_deal_t_var.deal_price);
				}catch(const std::exception& e){
					ERR("Convert \"deal_price\" to \"fprice_t\" fail! e={:}", e.what());
					throw e;
				}
			}else{
				ERR("\"deal_price\" not found in json!");
				return false;
			}
			if(json_var.find("deal_vol") != json_var.end()){
				try{
					const auto& json_var_deal_vol = json_var.at("deal_vol");
					json_var_deal_vol.get_to(tdx_xyzq_history_deal_t_var.deal_vol);
				}catch(const std::exception& e){
					ERR("Convert \"deal_vol\" to \"vol_share_t\" fail! e={:}", e.what());
					throw e;
				}
			}else{
				ERR("\"deal_vol\" not found in json!");
				return false;
			}
			if(json_var.find("deal_amount") != json_var.end()){
				try{
					const auto& json_var_deal_amount = json_var.at("deal_amount");
					json_var_deal_amount.get_to(tdx_xyzq_history_deal_t_var.deal_amount);
				}catch(const std::exception& e){
					ERR("Convert \"deal_amount\" to \"amount_t\" fail! e={:}", e.what());
					throw e;
				}
			}else{
				ERR("\"deal_amount\" not found in json!");
				return false;
			}
			if(json_var.find("commission") != json_var.end()){
				try{
					const auto& json_var_commission = json_var.at("commission");
					json_var_commission.get_to(tdx_xyzq_history_deal_t_var.commission);
				}catch(const std::exception& e){
					ERR("Convert \"commission\" to \"amount_t\" fail! e={:}", e.what());
					throw e;
				}
			}else{
				ERR("\"commission\" not found in json!");
				return false;
			}
			if(json_var.find("stamp_duty") != json_var.end()){
				try{
					const auto& json_var_stamp_duty = json_var.at("stamp_duty");
					json_var_stamp_duty.get_to(tdx_xyzq_history_deal_t_var.stamp_duty);
				}catch(const std::exception& e){
					ERR("Convert \"stamp_duty\" to \"amount_t\" fail! e={:}", e.what());
					throw e;
				}
			}else{
				ERR("\"stamp_duty\" not found in json!");
				return false;
			}
			if(json_var.find("transfer_fee") != json_var.end()){
				try{
					const auto& json_var_transfer_fee = json_var.at("transfer_fee");
					json_var_transfer_fee.get_to(tdx_xyzq_history_deal_t_var.transfer_fee);
				}catch(const std::exception& e){
					ERR("Convert \"transfer_fee\" to \"amount_t\" fail! e={:}", e.what());
					throw e;
				}
			}else{
				ERR("\"transfer_fee\" not found in json!");
				return false;
			}
			if(json_var.find("other_fees") != json_var.end()){
				try{
					const auto& json_var_other_fees = json_var.at("other_fees");
					json_var_other_fees.get_to(tdx_xyzq_history_deal_t_var.other_fees);
				}catch(const std::exception& e){
					ERR("Convert \"other_fees\" to \"amount_t\" fail! e={:}", e.what());
					throw e;
				}
			}else{
				ERR("\"other_fees\" not found in json!");
				return false;
			}
			if(json_var.find("remarks") != json_var.end()){
				try{
					const auto& json_var_remarks = json_var.at("remarks");
					json_var_remarks.get_to(tdx_xyzq_history_deal_t_var.remarks);
				}catch(const std::exception& e){
					ERR("Convert \"remarks\" to \"std::string\" fail! e={:}", e.what());
					throw e;
				}
			}else{
				ERR("\"remarks\" not found in json!");
				return false;
			}
		}catch (const std::exception& e){
			ERR("parse json {:} \nfail:{:}", json_var.dump(4), e.what());
			return false;
		}
		return true;
	}
	/* to json */
	static bool to_json(nlohmann::json& json_var, const tdx_xyzq_history_deal_t& tdx_xyzq_history_deal_t_var){
		try{
			json_var["date"] = tdx_xyzq_history_deal_t_var.date;
			json_var["time_format"] = tdx_xyzq_history_deal_t_var.time_format;
			json_var["time_utcSec"] = tdx_xyzq_history_deal_t_var.time_utcSec;
			json_var["stock_code"] = tdx_xyzq_history_deal_t_var.stock_code;
			json_var["stock_name"] = tdx_xyzq_history_deal_t_var.stock_name;
			json_var["id"] = tdx_xyzq_history_deal_t_var.id;
			json_var["opt_type"] = tdx_xyzq_history_deal_t_var.opt_type;
			json_var["deal_price"] = tdx_xyzq_history_deal_t_var.deal_price;
			json_var["deal_vol"] = tdx_xyzq_history_deal_t_var.deal_vol;
			json_var["deal_amount"] = tdx_xyzq_history_deal_t_var.deal_amount;
			json_var["commission"] = tdx_xyzq_history_deal_t_var.commission;
			json_var["stamp_duty"] = tdx_xyzq_history_deal_t_var.stamp_duty;
			json_var["transfer_fee"] = tdx_xyzq_history_deal_t_var.transfer_fee;
			json_var["other_fees"] = tdx_xyzq_history_deal_t_var.other_fees;
			json_var["remarks"] = tdx_xyzq_history_deal_t_var.remarks;
		}catch (const std::exception& e){
		ERR("to json {:} \nfail:{:}", json_var.dump(4), e.what());
			return false;
		}
		return true;
	}

	bool operator ==(const tdx_xyzq_history_deal_t& d) const
	{
		if (date == d.date &&
			time_format == d.time_format &&
			time_utcSec == d.time_utcSec &&
			stock_code == d.stock_code &&
			stock_name == d.stock_name &&
			id == d.id &&
			opt_type == d.opt_type &&
			deal_price == d.deal_price &&
			deal_vol == d.deal_vol &&
			deal_amount == d.deal_amount &&
			commission == d.commission &&
			stamp_duty == d.stamp_duty &&
			transfer_fee == d.transfer_fee &&
			other_fees == d.other_fees &&
			remarks == d.remarks)
		{
			return true;
		}
		return false;
	}

	bool operator !=(const tdx_xyzq_history_deal_t& d) const
	{
		return !((*this)==d);
	}

};// struct tdx_xyzq_history_deal_t
} // namespace S4


        /* Tester */
        inline int tdx_xyzq_history_deal_t_tester() {

            //std::ifstream i("G:/work2t/99_s3/s4/./json_template/tdx_xyzq_history_deal_t.json");
            std::string i("{    \"__assign_type_fields__\": {        \"date\":\"time_date_t\",         \"id\":\"int64_t\",         \"time_utcSec\":\"time_utcSec_t\",         \"deal_price\":\"fprice_t\",         \"deal_vol\":\"vol_share_t\",         \"deal_amount\":\"amount_t\",         \"commission\":\"amount_t\",         \"stamp_duty\":\"amount_t\",         \"transfer_fee\":\"amount_t\",         \"other_fees\":\"amount_t\"    },    \"__sqlite_capable__\" : true,    \"date\" : 20200507,    \"time_format\": \"19:55:30\",    \"time_utcSec\": 123,    \"stock_code\": \"002988\",    \"stock_name\": \"豪美新材\",    \"id\":26,    \"opt_type\":\"买入\",    \"deal_price\" : 0.0,    \"deal_vol\" : 27,    \"deal_amount\":0.0,    \"commission\":0.0,    \"stamp_duty\":0.0,    \"transfer_fee\":0.0,    \"other_fees\":0.0,    \"remarks\":\"起始配号:226168906\"}");
            nlohmann::json json_var;
            //i >> json_var; //from file
            json_var = nlohmann::json::parse(i);  //from string

            S4::tdx_xyzq_history_deal_t tdx_xyzq_history_deal_t_var;

            if(!S4::tdx_xyzq_history_deal_t::from_json(json_var, tdx_xyzq_history_deal_t_var)){
                INFO("S4::tdx_xyzq_history_deal_t::from_json fail!");
                return -1;
            }

            nlohmann::json j_out;
            if(!S4::tdx_xyzq_history_deal_t::to_json(j_out, tdx_xyzq_history_deal_t_var)){
                INFO("S4::tdx_xyzq_history_deal_t::to_json fail!");
                return -1;
            }

            INFO("{:}", j_out.dump(4));

            return 0;
        }

        